version: "3"
services:
  api:
    container_name: "v1"
    build: .
    restart: on-failure
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application -w 2
    volumes:
      - static_volume:/mortgage_service/static/
      - media_volume:/mortgage_service/media/
    env_file:
      - .env.prod
    expose:
      - 8000
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
     - 443:443
     - 80:80
    volumes:
     - static_volume:/mortgage_service/static/
     - media_volume:/mortgage_service/media/
     - certs:/etc/nginx/certs
     - html:/usr/share/nginx/html
     - vhost:/etc/nginx/vhost.d
     - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost: